repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.42.0  # Use latest stable Semgrep release
    hooks:
      - id: semgrep
        args:
          - --config=p/ci 
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3   # Use latest stable release
    hooks:
      - id: pip-audit
        args: ["--requirement", "requirements.txt"]




  
# Quick scan preset rules
