name: Gitleaks Secret Scan

on:
  push:
  pull_request:

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --no-git --source="." --report-format=json --report-path=gitleaks-report.json

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
